### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by izoratti-dianomic** [foglamp/FogLAMP#119]
https://github.com/foglamp/FogLAMP/blob/3357efec92ed72666020fbe54c8edb9de310145a/benchmarks/fogbench/__main__.py#L189

@MarkRiddoch, @praveen-garg and @billehunt 
If you pre-calculate this line, you have a performance boost of about 15%

**Comment by vaibhav-ScaleDB** [comment]
Resolved in https://github.com/foglamp/FogLAMP/pull/107
