### ISSUE TITLE
More performance on CoAP

### ISSUE THREAD

**Issue by izoratti-dianomic** [foglamp/FogLAMP#121]
https://github.com/foglamp/FogLAMP/blob/3357efec92ed72666020fbe54c8edb9de310145a/src/python/foglamp/device/coap/sensor_values.py#L147

@billehunt, @MarkRiddoch and @Terris-Dianomic 
Simply comment this line and the print for the PUT method

**Comment by Terris-Dianomic** [comment]
I didn't put this print in there.

**Comment by vaibhav-ScaleDB** [comment]
@izoratti-dianomic I guess you are looking in 170809.00 branch and not in develop. This change was a part of fogbench pull that you merged in 170809.00. You should have merged fogbench in 170809.00 branch without taking the changes in sensor_values.py
cc @praveen-garg

**Comment by vaibhav-ScaleDB** [comment]
Also, These print are for watching stuff on screen during development; these were planned to be removed / commented when it be in merge state. As we had to do early merge, so we can take care of this in another commit

**Comment by izoratti-dianomic** [comment]
> You should have merged fogbench in 170809.00 branch without taking the changes in sensor_values.py

My bad I did not look at the files that have been merged, but frankly I did not expect this change. 

I'd recommend to remerge develop and take everything but what's in the benchmark dir from develop.

**Comment by vaibhav-ScaleDB** [comment]
Fixed in https://github.com/foglamp/FogLAMP/pull/107
