### ISSUE TITLE
Testing the OMF Translator plugin against an HTTPS OMF endpoint

### ISSUE THREAD

**Issue by danielElopez** [foglamp/FogLAMP#432]
I see in the http://foglamp.readthedocs.io/en/master/05_testing.html#setting-the-omf-translator-plugin documentation that the example Connector Relay endpoint is HTTP, but I'd like to test against an HTTPS endpoint (using the new version of the Connector Relay that natively supports HTTPS).  That endpoint, though, uses a self-signed certificate, so I imagine that certificate validation would fail.  When I try to run the test outlined in the documentation, using the new HTTPS endpoint URL for my PI Connector Relay, I don't see any new AF Elements being created.  Is there a place where I can check for any OMF-related errors?

**Comment by sstefano69** [comment]
Hi Daniel,
the latest code in develop and the upcoming version 1.1  is going to support the https,
the URL should something like (using a different port, 5460) : 

'curl -H 'Content-Type: application/json' -X PUT -d '{ "value": "https://192.168.56.101:5460/ingress/messages" }' http://localhost:8081/foglamp/category/SEND_PR_1/URL;echo

FogLAMP 1.0 supports only http.

All the 'information' and 'errors' are traced in the syslog, 
so you could use for example : tail -f /var/log/syslog

**Comment by danielElopez** [comment]
Magnificent.  Thanks very much!  I'm looking forward to continuing test!

Regards,


Dan Lopez

Senior Systems Engineer

OSIsoft | 14701 Saint Marys Lane | Houston, TX 77079

Office: 510-347-2649 | Email: dlopez@osisoft.com


________________________________

**Comment by danielElopez** [comment]
Hello again!  Sorry to bother, but I wanted to follow up right quick and check about northbound OMF output over https, not http-and the docs still show the target being an http endpoint; do you have a rough idea of when OMF to HTTPS will be supported?

Thanks again,


Dan Lopez
[cid:image019.png@01D2CB2E.6969EF10]<http://www.osisoft.com/>
Senior Systems Engineer
OSIsoft<http://www.osisoft.com/> | Austin, TX
Office: 510-347-2649 | Email: dlopez@osisoft.com<mailto:dlopez@osisoft.com>
[cid:image020.png@01D2D8C5.3FA7BC80]<https://www.facebook.com/OSIsoft>  [cid:image021.png@01D2D8C5.3FA7BC80] <https://www.linkedin.com/company-beta/8822?pathWildcard=8822>   [cid:image022.png@01D2D8C5.3FA7BC80] <https://twitter.com/OSIsoft>   [cid:image023.png@01D2D8C5.3FA7BC80] <https://www.youtube.com/user/OSIsoftNews>   [cid:image024.png@01D2D8C5.3FA7BC80] <https://pisquare.osisoft.com/welcome>
[PI_World_Email_Sig]<https://piworld.osisoft.com/US2018?utm_campaign=UC2018&utm_medium=email&utm_source=email-signature&utm_content=OSIsoft&utm_term=General>

**Comment by izoratti-dianomic** [comment]
Hi Daniel, 

You are referring to the documentation available for the current master branch, and you are absolutely right, we sill refer to the HTTP endpoint. Master and its documentation has been frozen with version 1.1.1 of FogLAMP, which has an HTTP-based North Task Plugin.

If you look at the new documentation in the develop branch (see here: http://foglamp.readthedocs.io/en/develop/05_testing.html?highlight=HTTPS <http://foglamp.readthedocs.io/en/develop/05_testing.html?highlight=HTTPS> ) we refer to the HTTPS endpoint and Connector Relay OMF 1.2. We are planning to release the next version of FogLAMP the week of March 12: at that point, the HTTPS endpoint will be documented in the master branch.

Thanks!
-ivan

— 
Ivan Zoratti - Co-founder and CPO 
Dianomic Systems
www.dianomic.com
