### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [foglamp/FogLAMP#746]
Greetings, I just made a logo for your project, hope you like it.
![foglamp1](https://user-images.githubusercontent.com/35619342/39305874-98fc0f92-492c-11e8-9515-6c004e0f85e7.png)
![foglamp11](https://user-images.githubusercontent.com/35619342/39305876-9a14b6d6-492c-11e8-9174-fb8b7274b448.png)
In case you liked it, let me know which variation and I'll upload the files on a pull request. Also please let me know if you me to add/modify something. :)

**Comment by izoratti** [comment]
Hi @michaelizer - Thank you for your message! We actually have a logo for FogLAMP, we have not been very good in showing it.

Please keep going supporting FogLAMP!
