### ISSUE TITLE
Error while sending OMF messages from FogLAMP to Pi Connector Relay/Pi Server

### ISSUE THREAD

**Issue by priyasehgal** [foglamp/FogLAMP#934]
Hi,
I have enabled schedule for sending the FogLAMP readings to North (Pi Server) and have set Producer Token and Ingress URL as shown in Pi Data Collection Manager as follows: 

> curl -s http://localhost:8081/foglamp/schedule/2b614d26-760f-11e7-b5a5-be2e44b06b34 | jq
{
  "day": null,
  "id": "2b614d26-760f-11e7-b5a5-be2e44b06b34",
  "enabled": true,
  "time": 0,
  "repeat": 30,
  "type": "INTERVAL",
  "exclusive": true,
  "processName": "North Readings to PI",
  "name": "OMF to PI north"
}

> curl -X GET http://localhost:8081/foglamp/category/SEND_PR_1 | jq
{
  "applyFilter": {
....... <More fields>

"URL": {
    "type": "string",
    "value": "https://ibmx3530m3-52-20:5460/ingress/messages",
    "default": "https://pi-server:5460/ingress/messages",
    "description": "The URL of the PI Connector to send data to"
  },

 "producerToken": {
    "type": "string",
    "value": "uid=3d2e6c31-746e-4bd9-8ada-cc8e286b441a&crt=20180716235212830&sig=6asBQ1ceQZAMsHPOmdbZb0stGz2Paye4KEUzuXN3/eQ=",
    "default": "omf_north_0001",
    "description": "The producer token that represents this FogLAMP stream"
  },
..... <Some more Parameters>

}
Yet, I do not see anything on Pi Asset Framework Ingested. 
I looked up the /var/log/syslog and found these error messages - please help me resolve the problem.

**Error Message from syslog:** 
WARNING: omf: omf_north_1: an error occurred during the request to the destination - error details |HTTPSConnectionPool(host='ibmx3530m3-52-20', port=5460): Max retries exceeded with url: /ingress/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff276fe33c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))|
Jul 16 13:11:52 scspa0501709001 FogLAMP[31799] ERROR: omf: omf_north_1: cannot complete the sending operation - error details |an error occurred during the request to the destination - error details |HTTPSConnectionPool(host='ibmx3530m3-52-20', port=5460): Max retries exceeded with url: /ingress/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff276fe33c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))||#012Traceback (most recent call last):#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 396, in plugin_send#012    omf_north.create_omf_objects(raw_data, config_category_name, type_id)#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 221, in wrapper#012    result = _function(*arg)#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 693, in create_omf_objects#012    self._create_omf_objects_automatic(item)#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 541, in _create_omf_objects_automatic#012    typename, omf_type = self._create_omf_type_automatic(asset_info)#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 581, in _create_omf_type_automatic#012    self.send_in_memory_data_to_picromf("Type", omf_type[typename])#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 221, in wrapper#012    result = _function(*arg)#012  File "/usr/local/foglamp/python/foglamp/plugins/north/omf/omf.py", line 754, in send_in_memory_data_to_picromf#012    raise _error#012Exception: an error occurred during the request to the destination - error details |HTTPSConnectionPool(host='ibmx3530m3-52-20', port=5460): Max retries exceeded with url: /ingress/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff276fe33c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))|
Jul 16 13:11:52 scspa0501709001 FogLAMP[31799] ERROR: sending_process: sending_process_1: cannot complete the sending operation of a block of data.
Jul 16 13:11:52 scspa0501709001 FogLAMP[31799] ERROR: sending_process: sending_process_1: cannot complete the sending operation - error details |an error occurred during the request to the destination - error details |HTTPSConnectionPool(host='ibmx3530m3-52-20', port=5460): Max retries exceeded with url: /ingress/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff276fe33c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))||

**Comment by praveen-garg** [comment]
@priyasehgal  Please check your web proxy and firewall. Are you able to ping `ibmx3530m3-52-20` ?

**Comment by priyasehgal** [comment]
Thanks. I did not provide the complete hostname. It works now.
