### ISSUE TITLE
FogLAMP facing problem while sending data to OSISoft

### ISSUE THREAD

**Issue by priyasehgal** [foglamp/FogLAMP#960]
I have setup FogLAMP and also the URL and producerToken to send the data. 
There were some problems initially with respect to the security settings of the Pi Points and I set correct Security Settings. Using Data Collection Manager I have created the Pipeline. 
However, I might be missing something on the AF setup because whenever I ingest data into FogLAMP and it goes through the north Plugin (OMF) - on FogLAMP the SENT stats increase, but on the OSISoft (DCM) I am seeing this error:
Do I need to create some template - what should be the format, etc.?
NOTE: I am only interested in the data getting ingested into Pi Archive from FogLAMP OMF - but because of following errors Pi Points are not getting created. 

 Error while checking in the pending changes: Cannot complete the operation because the user does not have rights to write to ElementTemplate 'OMF.FogLAMP Connector.0001_D_CAB/A_typename_sensor' with UniqueID 'bd2be362-4922-4e3a-83cc-baa402d43d77'. AF assets will be checked-in when a new value is sent. Full exception: OSIsoft.Tau.AssetCache.AFCheckInException: Error while checking in the pending changes: Cannot complete the operation because the user does not have rights to write to ElementTemplate 'OMF.FogLAMP Connector.0001_D_CAB/A_typename_sensor' with UniqueID 'bd2be362-4922-4e3a-83cc-baa402d43d77'. ---> System.Security.SecurityException: Cannot complete the operation because the user does not have rights to write to ElementTemplate 'OMF.FogLAMP Connector.0001_D_CAB/A_typename_sensor' with UniqueID 'bd2be362-4922-4e3a-83cc-baa402d43d77'. at OSIsoft.AF.PISystem.CheckServerError(dcServerError err, Boolean firstAttempt) at OSIsoft.AF.Support.AFSerialProxy.Call(String rpcName, ProxyDelegate codeBlock) at OSIsoft.AF.Support.AFSerialProxy.CheckInElementTemplate(dcElementTemplate[] changes, dcObjectIdentity[] deletedIdentities, Guid[] elementsWithAutoCreatedAnalyses, Boolean& updatedUOM, Int64[]& securityIds) at OSIsoft.AF.Asset.AFElementTemplate.RemoteCheckInElementTemplate(AFDatabase database, HashSet`1 processedItems, dcElementTemplate[] changes, dcObjectIdentity[] deletedIdentities, Guid[] elementsWithAutoCreatedAnalyses) at OSIsoft.AF.AFDatabase.SaveElementTemplates(Boolean doCheckIn, HashSet`1 processedItems, List`1 appliedList, HashSet`1 elementsWithAutoCreatedAnalysesList, List`1& changeList, List`1& deleteList) at OSIsoft.AF.AFDatabase.ProcessDatabaseApplyCheckInChanges(ProcessMode mode, AFCheckedOutMode checkedOutMode, IEnumerable`1 objList, List`1 appliedList, HashSet`1 elementsWithAutoCreatedObjects, Boolean& dbPagedRefreshRequired) at OSIsoft.AF.AFDatabase.ProcessDatabaseChanges(ProcessMode mode, AFCheckedOutMode checkedOutMode, IEnumerable`1 objList, List`1 appliedList, HashSet`1 elementsWithAutoCreatedObjects) at OSIsoft.AF.AFDatabase.ProcessDatabaseChanges(ProcessMode mode, AFCheckedOutMode checkedOutMode) at OSIsoft.AF.AFDatabase.CheckIn(AFCheckedOutMode mode) at OSIsoft.Tau.AF.Common.ConnectorDestinationMapper.CommitChanges(AFCheckedOutMode mode) at OSIsoft.Tau.AF.Common.AFContext.CommitChanges(AFCheckedOutMode mode) --- End of inner exception stack trace --- at OSIsoft.Tau.AF.Common.AFContext.CommitChanges(AFCheckedOutMode mode) at OSIsoft.Tau.PI.AssetBuilder.AFAssetBuilder.AddValueLinksToTemplate(AFElementTemplate template, Dictionary`2 valueStreamLinks, String connectorType, String connectorUid) at OSIsoft.Tau.PI.AssetBuilder.AFAssetBuilder.AddStreams(AFElement elementToUpdate, Dictionary`2 valueStreamLinks, String connectorType, String connectorUid) at OSIsoft.Tau.PI.AssetBuilder.AFAssetBuilder.AddStreams(AssetNode assetNode, Dictionary`2 valueStreamLinks) at OSIsoft.Tau.AssetCache.AssetCache.ProcessLink(AssetLink link) at OSIsoft.Tau.AssetCache.AssetCache.PostLink(TauEvent link, String streamId) at OSIsoft.Tau.AssetCache.AssetCache.FlushAsync(AssetCacheBatch batch) 

One more error seen is:
Unable to persist entities to repository: C:\ProgramData\OSIsoft\Tau\Relay.ConnectorHost\SchemaRepository\FogLAMP/schemas.json. Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute. at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext() at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonConverter[] converters) at OSIsoft.Tau.Relay.Translator.REST.TypeRepository.<>c__DisplayClass26_0`1.<WriteToDisk>b__0().

**Comment by ashwinscale** [comment]
Hi Priya, 

The OMF Connector Relay created the element templates on your behalf, prior to creating the elements themselves. It looks as though the Pi Connector does not a have access to create the element templates. The Pi Connector Administration Guide outlines preinstallation steps including "Required access summary". Please review and implement the needed requirements to allow the Pi Connector and DCM to properly create data.
